Converts IneligibleStudent model to typescript
UPchieve/server pull request #494
Opened 2020-10-15 20:54 UTC by thedevelopnik

Links
-----
- Issue: https://github.com/UPchieve/server/issues/490

Description
-----------
- Converts IneligibleStudent model to typescript, from the large models PR

Developer self-review checklist
-------------------------------
- [x] Potentially confusing code has been explained with comments
- [x] No warnings or errors have been introduced; all known error cases have been handled
- [x] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [x] All edge cases have been addressed

2020-10-15 21:19 UTC, treykris requested changes

2020-10-15 21:19 UTC, treykris commented on models/IneligibleStudent.ts
> +  ipAddress: String
Missing the `referredBy` property in the Schema and in the interface

2020-10-15 21:42 UTC, thedevelopnik commented on models/IneligibleStudent.ts
> +  ipAddress: String
Good catch, this is the other reason to do this one at a time, catching the little things that have gone out of date

2020-10-15 21:43 UTC, thedevelopnik commented
This now touches the User.ts model, but just enough to get this one to work. Will need to swing back around and make sure that's fully updated but didn't want to intertwine it to much with this now.

2020-10-15 22:35 UTC, treykris commented on models/IneligibleStudent.ts
> +  referredBy: Types.ObjectId | User
I think we might have some luck with this one! We will actually be able to get away without having the union type here. I couldn't find any place in the codebase that we're currently using the `referredBy` on this interface as a `User` type. I think we can hold off on it and leave a @todo comment for adding the union type with `User` and have it as:

```
referredBy: Types.ObjectId
```

 for now, until we get `User.ts` merged. Especially since it looks like `User.ts`  is also importing `import { Session } from './Session'` and then we'd have to also include those models `Session.ts` depends on

2020-10-15 22:42 UTC, treykris commented on models/User.ts
> +import { Session } from './Session'
Now that I think about it - another option we can do is remove `pastSessions` on the user interface to avoid having to import `Session` here

2020-10-15 22:46 UTC, treykris commented on models/IneligibleStudent.ts
> +import { User } from './User'
Sorry for going comment crazy haha

Let's import this from `models/types` and put a comment to change it to import from User.ts when converted

2020-10-16 15:14 UTC, thedevelopnik commented on models/IneligibleStudent.ts
> +import { User } from './User'
I like that plan, I'll make the changes.

2020-10-20 14:24 UTC, treykris requested changes
Looks good!!

2020-10-20 14:29 UTC, treykris approved these changes

2020-10-20 14:36 UTC, merged